### ISSUE TITLE
Is this still maintained? looking for `comment_allowed` in the `LnurlPayResponse`

### ISSUE THREAD

**Issue by brianoflondon** [lnbits/lnurl#10]
Was just wondering if this repo is still useable?

I was looking for `comment_allowed` in the `LnurlPayResponse` and it doesn't seem to be there. Not sure if I should use this library or just rebuild.

**Comment by eillarra** [comment]
You will need to talk to the LNbits team, I am not the maintainer anymore. I cannot give you access to the repo but they might...

**Comment by arcbtc** [comment]
Yay DNI! And helllllooooo Eneko 👋

**Comment by brianoflondon** [comment]
I added #12 to fix this issue and I checked @dni #11 and all the tests run for me.

**Comment by dni** [comment]
merged
