### ISSUE TITLE
Error message after updating lnbits/lnurlw

### ISSUE THREAD

**Issue by SovereignCraft** [lnbits/lnurl#25]
After updating LNBits I am getting the following error in the LNURLw extension as a pop up at the bottom of the screen:

'URL' object has no attribute 'encode'
500 INTERNAL SERVER ERROR

I am not yet sure where this error is being generated. LNURLp works fine. The error is generated when the list of LNURLw links attempts to be listed. They are not listed, APIs do not work. Also the Error does not come up if the user does not have any existing LNURLw links made, but only upon creating their first one. After a user has one that should be listed the error is generated upon each page reload.

**Comment by dni** [comment]
did you run `poetry install` maybe you still having an old version of `lnurl` installed in your virtual env

**Comment by SovereignCraft** [comment]
Not sure what happened, But after deleting the Extension and data, it was fine. Must have been an old/malformed entry on an LNURL somewhere.
