### ISSUE TITLE
LNURL CLI client

### ISSUE THREAD

**Issue by Kixunil** [lnbits/lnurl#3]
I'd like to write a CLI client for LNURL, so far only for `lnurl-channel`, but I'm open to do more stuff in the future. (And a GUI later too!) I think it'd be useful to do with collaboration with your repository/org, so that it's easier to find for people and hopefully attracts more contributors.

If you're interested, I'd like to know how exactly I should do it.

* Should this be a separate repo that will be dded to the org?
* Should it be a part of `lnurl` python package or a completely new package?
* How should the command be called? Just `lnurl` or `lnurlcli`?

BTW, I also wrote [`lnch-vekslak`](http://github.com/Kixunil/lnch-vekslak) a long time ago before this lib existed. I'm willing to refactor it and join forces with it too, if you're interested. It's not a high-priority task for me right now, though.

**Comment by eillarra** [comment]
Sure, I think it can be integrated in the library, we can then have a option to install the CLI and its dependencies with `pip install lnurl[cli]` (via extras_require).

What do you think, @jogc ?

**Comment by eillarra** [comment]
I suggest using something like `click` to simplify development and avoid reinventing the wheel: https://click.palletsprojects.com/en/7.x/

**Comment by jogc** [comment]
> Sure, I think it can be integrated in the library, we can then have a option to install the CLI and its dependencies with `pip install lnurl[cli]` (via extras_require).
> 
> What do you think, @jogc ?

Sounds good 👍🏻

**Comment by Kixunil** [comment]
Thanks for the answer! `click` looks great, will definitely use it. I have some other stuff to do right now, but I expect to have something finished in a few weeks.
