### ISSUE TITLE
(Minor) #31 removed `MilliSatoshi` from types

### ISSUE THREAD

**Issue by AngusP** [lnbits/lnurl#39]
https://github.com/lnbits/lnurl/pull/31/ removed the `MilliSatoshi` which some users might have imported, implicitly replacing it with `bolt11.MilliSatoshi`. Might be worth mentioning in the changelog as it's a 'breaking' change for anyone using hints

**Comment by dni** [comment]
thanks for reporting, what do you think if we just export the `bolt11.MilliSatoshi` from the lnurl `__init__`
