### ISSUE TITLE
RFC3986 validator too strict?

### ISSUE THREAD

**Issue by eillarra** [lnbits/lnurl#6]
I propose we don't use the validator by default, and just let the developers decide if they want to use it.
Currently we are forcing this validation, here: https://github.com/lnbits/lnurl/blob/master/lnurl/types.py#L16

We can just change the line so it reads:

> STRICT_RFC3986 = os.environ.get("LNURL_STRICT_RFC3986", "0") == "1"

@jogc, what do you think?

**Comment by jogc** [comment]
Yep, that's the way it worked in my original module as well
